[
  {
    resource: "/project/workspace/src/components/Presentation.tsx",
    owner: "typescript",
    code: "2307",
    severity: 8,
    message:
      "Cannot find module 'swiper/react' or its corresponding type declarations.",
    source: "ts",
    startLineNumber: 2,
    startColumn: 37,
    endLineNumber: 2,
    endColumn: 51,
  },
  {
    resource: "/project/workspace/src/components/Presentation.tsx",
    owner: "typescript",
    code: "2307",
    severity: 8,
    message:
      "Cannot find module 'swiper/modules' or its corresponding type declarations.",
    source: "ts",
    startLineNumber: 3,
    startColumn: 50,
    endLineNumber: 3,
    endColumn: 66,
  },
  {
    resource: "/project/workspace/src/components/Presentation.tsx",
    owner: "typescript",
    code: "2307",
    severity: 8,
    message:
      "Cannot find module 'swiper' or its corresponding type declarations.",
    source: "ts",
    startLineNumber: 4,
    startColumn: 43,
    endLineNumber: 4,
    endColumn: 51,
  },
  {
    resource: "/project/workspace/src/components/Presentation.tsx",
    owner: "typescript",
    code: "2307",
    severity: 8,
    message:
      "Cannot find module '../context/PresentationContext' or its corresponding type declarations.",
    source: "ts",
    startLineNumber: 5,
    startColumn: 33,
    endLineNumber: 5,
    endColumn: 65,
  },
  {
    resource: "/project/workspace/src/components/Presentation.tsx",
    owner: "typescript",
    code: "2307",
    severity: 8,
    message:
      "Cannot find module './SlideNavigation' or its corresponding type declarations.",
    source: "ts",
    startLineNumber: 6,
    startColumn: 29,
    endLineNumber: 6,
    endColumn: 48,
  },
  {
    resource: "/project/workspace/src/components/Presentation.tsx",
    owner: "typescript",
    code: "7016",
    severity: 8,
    message:
      "Could not find a declaration file for module './slides/Slide01'. '/project/workspace/src/components/slides/Slide01.jsx' implicitly has an 'any' type.",
    source: "ts",
    startLineNumber: 14,
    startColumn: 21,
    endLineNumber: 14,
    endColumn: 39,
  },
  {
    resource: "/project/workspace/src/components/Presentation.tsx",
    owner: "typescript",
    code: "7016",
    severity: 8,
    message:
      "Could not find a declaration file for module './slides/Slide29'. '/project/workspace/src/components/slides/Slide29.jsx' implicitly has an 'any' type.",
    source: "ts",
    startLineNumber: 15,
    startColumn: 21,
    endLineNumber: 15,
    endColumn: 39,
  },
  {
    resource: "/project/workspace/src/components/Presentation.tsx",
    owner: "typescript",
    code: "2307",
    severity: 8,
    message:
      "Cannot find module './slides/Slide44' or its corresponding type declarations.",
    source: "ts",
    startLineNumber: 16,
    startColumn: 21,
    endLineNumber: 16,
    endColumn: 39,
  },
  {
    resource: "/project/workspace/src/components/Presentation.tsx",
    owner: "typescript",
    code: "2503",
    severity: 8,
    message: "Cannot find namespace 'JSX'.",
    source: "ts",
    startLineNumber: 34,
    startColumn: 26,
    endLineNumber: 34,
    endColumn: 29,
  },
  {
    resource: "/project/workspace/src/components/Presentation.tsx",
    owner: "typescript",
    code: "7006",
    severity: 8,
    message: "Parameter 'swiper' implicitly has an 'any' type.",
    source: "ts",
    startLineNumber: 71,
    startColumn: 20,
    endLineNumber: 71,
    endColumn: 26,
  },
  {
    resource: "/project/workspace/src/components/Presentation.tsx",
    owner: "typescript",
    code: "7006",
    severity: 8,
    message: "Parameter 'swiper' implicitly has an 'any' type.",
    source: "ts",
    startLineNumber: 72,
    startColumn: 25,
    endLineNumber: 72,
    endColumn: 31,
  },
];
